import React, { FC } from "react";

import Layout from "@/components/layout/Layout";
import { ICar, ICarData } from "@/interfaces/car.interface";
import CarItem from "@/components/pages/car/CarItem";

import styles from "./Home.module.scss";

const Home: FC<ICarData> = ({ cars }) => {
  return (
    <Layout title="Home" description="Cars catalog">
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <div className={styles.listCard}>
        {cars?.length ? (
          cars.map((car: ICar) => <CarItem key={car?.id} car={car} />)
        ) : (
          <div>Car not found</div>
        )}
      </div>
    </Layout>
  );
};

export default Home;
